AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  Setup the security groups for MyApp. 

Parameters:
  VPC:
    Description: VPC to deploy to
    Type: AWS::EC2::VPC::Id

Resources:

  # --- Security Groups ---
  MyAppALBSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupName: ALBSG
      GroupDescription: SG for MyApp ALB
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

  MyAppSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: MyAppSG
      GroupDescription: SG for MyApp
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: TCP
          FromPort: 80
          ToPort: 80
          SourceSecurityGroupId: !Ref MyAppALBSG

Outputs:
  MyAppALBSG:
    Description: MyApp ALB SG ID
    Value: !Ref MyAppALBSG
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", 'ALBSG:id']]
  
  MyAppSG:
    Description: MyApp compute SG ID
    Value: !Ref MyAppSG
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", 'SG:id']]