AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Network ACL Entries. 

Parameters:
  VPCStackName:
    Description: Name of the stack that created the VPC. 
    Type: String

Resources:

  # --- Public Subnet Network ACLs ---
  # --- INGRESS RULES ---
  # --- Rule 10: Wide Open
  PublicIngressRule10:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId: 
        Fn::ImportValue: !Join [":", [!Ref VPCStackName, "public-nacl:id"]]
      Protocol: -1
      RuleAction: allow
      RuleNumber: 10


  # -- EGRESS RULES ---

  PublicEgressRule10:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: 
        Fn::ImportValue: !Join [":", [!Ref VPCStackName, "public-nacl:id"]]
      Protocol: -1
      RuleAction: allow
      RuleNumber: 10
  

  # --- Private Subnet Network ACLs ---
  # --- INGRESS RULES ---

  PrivateIngressRule10:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: false
      NetworkAclId: 
        Fn::ImportValue: !Join [":", [!Ref VPCStackName, "private-nacl:id"]]
      Protocol: -1
      RuleAction: allow
      RuleNumber: 10


  # --- EGRESS RULES ---

  PrivateEgressRule10:
    Type: AWS::EC2::NetworkAclEntry
    Properties: 
      CidrBlock: 0.0.0.0/0
      Egress: true
      NetworkAclId: 
        Fn::ImportValue: !Join [":", [!Ref VPCStackName, "private-nacl:id"]]
      Protocol: -1
      RuleAction: allow
      RuleNumber: 10
